### ISSUE TITLE
class43 paving tail 对于 10,10 的测试用例会溢出

### ISSUE THREAD

**Issue by ImSingee** [algorithmzuo/algorithmbasic2020#13]
建议将类型修改为 long 或是取模

对于 10,10 的用例，目前输出是 `886008608`

在将 ways3 的数据类型修改为 long 后

```java
        public static long ways3(int N, int M) {
		if (N < 1 || M < 1 || ((N * M) & 1) != 0) {
			return 0;
		}
		if (N == 1 || M == 1) {
			return 1;
		}
		int max = Math.max(N, M);
		int min = Math.min(N, M);
		int pre = (1 << min) - 1;
		long[][] dp = new long[1 << min][max + 1];
		for (int i = 0; i < dp.length; i++) {
			for (int j = 0; j < dp[0].length; j++) {
				dp[i][j] = -1;
			}
		}
		return process3(pre, 0, max, min, dp);
	}

	public static long process3(int pre, int i, int N, int M, long[][] dp) {
		if (dp[pre][i] != -1) {
			return dp[pre][i];
		}
		long ans = 0;
		if (i == N) {
			ans = pre == ((1 << M) - 1) ? 1 : 0;
		} else {
			int op = ((~pre) & ((1 << M) - 1));
			ans = dfs3(op, M - 1, i, N, M, dp);
		}
		dp[pre][i] = ans;
		return ans;
	}

	public static long dfs3(int op, int col, int level, int N, int M, long[][] dp) {
		if (col == -1) {
			return process3(op, level + 1, N, M, dp);
		}
		long ans = 0;
		ans += dfs3(op, col - 1, level, N, M, dp);
		if (col > 0 && (op & (3 << (col - 1))) == 0) {
			ans += dfs3((op | (3 << (col - 1))), col - 2, level, N, M, dp);
		}
		return ans;
	}
```

输出为 258584046368

**Comment by AMchuAMchuAMchu** [comment]
邮件已收到！谢谢！

**Comment by algorithmzuo** [comment]
> 建议将类型修改为 long 或是取模
> 
> 对于 10,10 的用例，目前输出是 `886008608`
> 
> 在将 ways3 的数据类型修改为 long 后
> 
> ```java
>         public static long ways3(int N, int M) {
> 		if (N < 1 || M < 1 || ((N * M) & 1) != 0) {
> 			return 0;
> 		}
> 		if (N == 1 || M == 1) {
> 			return 1;
> 		}
> 		int max = Math.max(N, M);
> 		int min = Math.min(N, M);
> 		int pre = (1 << min) - 1;
> 		long[][] dp = new long[1 << min][max + 1];
> 		for (int i = 0; i < dp.length; i++) {
> 			for (int j = 0; j < dp[0].length; j++) {
> 				dp[i][j] = -1;
> 			}
> 		}
> 		return process3(pre, 0, max, min, dp);
> 	}
> 
> 	public static long process3(int pre, int i, int N, int M, long[][] dp) {
> 		if (dp[pre][i] != -1) {
> 			return dp[pre][i];
> 		}
> 		long ans = 0;
> 		if (i == N) {
> 			ans = pre == ((1 << M) - 1) ? 1 : 0;
> 		} else {
> 			int op = ((~pre) & ((1 << M) - 1));
> 			ans = dfs3(op, M - 1, i, N, M, dp);
> 		}
> 		dp[pre][i] = ans;
> 		return ans;
> 	}
> 
> 	public static long dfs3(int op, int col, int level, int N, int M, long[][] dp) {
> 		if (col == -1) {
> 			return process3(op, level + 1, N, M, dp);
> 		}
> 		long ans = 0;
> 		ans += dfs3(op, col - 1, level, N, M, dp);
> 		if (col > 0 && (op & (3 << (col - 1))) == 0) {
> 			ans += dfs3((op | (3 << (col - 1))), col - 2, level, N, M, dp);
> 		}
> 		return ans;
> 	}
> ```
> 
> 输出为 258584046368

如果方法数很多，题目一定会让你取mod，比如对1000000007取余数。所以long类型也不一定够用，这个题就单纯的展示思路了。不改long了，因为如果方法数更多反正也需要去做取余数操作的。

**Comment by AMchuAMchuAMchu** [comment]
邮件已收到！谢谢！
