### ISSUE TITLE
左老师 请问能不能把您上课的ppt分享一下

### ISSUE THREAD

**Issue by mark9714** [algorithmzuo/algorithmbasic2020#4]

**Comment by algorithmzuo** [comment]
这有一份笔记，你看看吧。希望能对你有帮助。https://shimo.im/docs/68cd6h3TwygPwx8W/read

**Comment by Lawliet1250** [comment]
> 这有一份笔记，你看看吧。希望能对你有帮助。https://shimo.im/docs/68cd6h3TwygPwx8W/read
老师，这份文档公开访问受限，怎么办啊

**Comment by AMchuAMchuAMchu** [comment]
邮件已收到！谢谢！
